import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./Footer/page"; // <-- Footer import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Navbar - 10% */}
          <div className="h-[10vh]">
            <Navbar />
          </div>

          {/* Main Content - 80% */}
          <main className="flex-1 h-[80vh] overflow-auto bg-white">
            {children}
          </main>

          {/* Footer - 10% */}
          <div className="h-[10vh]">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
